// Create a map object
var myMap = L.map("map", {
  center: [37.09, -95.71],
  zoom: 5
});

// Add a tile layer
L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}", {
  attribution: "Map data &copy; <a href=\"https://www.openstreetmap.org/\">OpenStreetMap</a> contributors, <a href=\"https://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>, Imagery © <a href=\"https://www.mapbox.com/\">Mapbox</a>",
  maxZoom: 18,
  id: "mapbox.streets",
  accessToken: API_KEY
}).addTo(myMap);

// An array containing all data
var menus = 
[{location: [-38.0, 145.0],
  top_words: "['Champagne,', 'Liqueurs,', 'Mineral', 'Waters,', '&']"},
 {location: [-37.0, 175.0],
  top_words: "['de', 'Ã\x83', 'la', 'HuÃ\x83Â®tres', 'Royales']"},
 {location: [-35.0, 139.0],
  top_words: "['Broiled', 'mutton', 'with', 'Strawberries', 'Jam']"},
 {location: [-25.0, 134.0],
  top_words: "['of', 'Sauce', 'Green', 'Olives', 'Caviar']"},
 {location: [-23.0, -43.0],
  top_words: "['with', 'of', 'Steak', 'Fried', 'Eggs']"},
 {location: [-8.0, 115.0],
  top_words: "['of', 'en', 'au', 'Sur', 'Cream']"},
 {location: [7.0, 80.0],
  top_words: "['Cheese', 'a', 'la', 'Fried', 'Coffee']"},
 {location: [14.0, 101.0],
  top_words: "['and', 'Consomme', 'mit', 'a', 'la']"},
 {location: [14.0, 121.0],
  top_words: "['Beefsteak,', 'au', 'mit', 'potatoes', 'Boiled']"},
 {location: [15.0, 121.0],
  top_words: "['Roast', 'Succotash', 'with', '&', 'in']"},
 {location: [18.0, -70.0],
  top_words: "['with', 'Green', 'style', 'Chicken-broth', 'Veal-dumplings']"},
 {location: [18.0, -65.0],
  top_words: "['de', 'Salade', 'Clovis', 'Consomme', 'Tortue']"},
 {location: [19.0, 73.0],
  top_words: "['beef', 'salad', 'cream', 'consomme,', 'Spaghetti']"},
 {location: [22.0, -98.0],
  top_words: "['Puchero', 'Heilbutt-Steak', 'mit', 'feinen', 'Krautern']"},
 {location: [22.0, 73.0], 'top_words': "['a', 'la', 'en', 'du', 'sauce']"},
 {location: [23.0, -82.0],
  top_words: "['Club', 'Old', 'St.', 'or', 'Rye']"},
 {location: [23.0, 88.0],
  top_words: "['Broiled', '(to', 'order)', 'Fried', 'Cakes']"},
 {location: [25.0, -77.0],
  top_words: "['and', 'with', 'of', 'Potatoes', 'Beef']"},
 {location: [26.0, -98.0],
  top_words: "['Cold', 'Eggs', 'Chicken', 'Fried', 'Apple']"},
 {location: [26.0, -82.0],
  top_words: "['Roast', 'of', 'Chicken', 'beans', 'Potatoes']"},
 {location: [26.0, -80.0], 'top_words': "['a', 'la', 'of', 'and', 'de']"},
 {location: [27.0, -80.0],
  top_words: "['with', 'Beef', 'Pie', 'Cold', 'Cream']"},
 {location: [28.0, -83.0],
  top_words: "['a', 'Sauce', 'la', 'of', 'Cheese']"},
 {location: [28.0, -82.0],
  top_words: "['and', 'Cold', 'de', 'Broiled', 'Boiled']"},
 {location: [29.0, -95.0], 'top_words': "['de', 'en', 'aux', 'a', 'tasse']"},
 {location: [29.0, -81.0],
  top_words: "['Cold:', 'and', 'Cheese', 'Beef', 'Chicken']"},
 {location: [30.0, -98.0],
  top_words: "['a', 'la', 'Taubensuppe', 'Consomme', 'mit']"},
 {location: [30.0, -96.0],
  top_words: "['Filet', 'of', 'Sauce', 'Potatoes', 'a']"},
 {location: [30.0, -93.0],
  top_words: "['Broiled', 'in', '-', 'Fried', 'Omelet']"},
 {location: [30.0, -90.0],
  top_words: "['with', 'Potatoes', 'Fried', 'Coffee', 'Steak']"},
 {location: [30.0, -82.0],
  top_words: "['with', 'a', 'la', 'Steak', 'Extra']"},
 {location: [30.0, -81.0],
  top_words: "['la', 'a', 'with', 'de', 'Sauce']"},
 {location: [31.0, -88.0],
  top_words: "['a', 'la', 'Roast', 'and', 'Ribs']"},
 {location: [31.0, 121.0],
  top_words: "['Broiled', 'Potatoes', 'Fried', 'and', 'Bacon']"},
 {location: [32.0, -111.0],
  top_words: "['Baked', 'Roast', 'Potatoes', 'Fruits', 'Bouillon']"},
 {location: [32.0, -106.0],
  top_words: "['a', 'la', 'of', 'Sweet', 'with']"},
 {location: [32.0, -97.0],
  top_words: "['a', 'la', 'mit', 'with', 'Fried']"},
 {location: [32.0, -93.0],
  top_words: "['Cold', '&', 'Herrings', 'Beef', 'Pigs']"},
 {location: [32.0, -86.0],
  top_words: "['-', 'of', 'Pommes', 'Celery', 'Salted']"},
 {location: [32.0, -65.0],
  top_words: "['with', 'sauce', 'la', 'of', 'en']"},
 {location: [32.0, 35.0],
  top_words: "['of', 'Pommes', 'Cheese', 'Bleu', 'Point']"},
 {location: [33.0, -117.0],
  top_words: "['with', 'Omelette', '&', 'Fried', 'Broiled']"},
 {location: [33.0, -112.0],
  top_words: "['la', 'Sauce', 'a', 'Roast', 'and']"},
 {location: [33.0, -100.0],
  top_words: "['a', 'la', 'of', 'Potatoes', 'BLUE']"},
 {location: [33.0, -97.0], 'top_words': "['a', 'de', 'la', 'of', 'au']"},
 {location: [33.0, -80.0],
  top_words: "['green', 'Potatoes', 'of', 'a', 'la']"},
 {location: [34.0, -119.0], 'top_words': "['&', 'of', 'a', 'Coffee', 'in']"},
 {location: [34.0, -118.0],
  top_words: "['with', 'a', 'la', 'of', 'cream']"},
 {location: [34.0, -116.0],
  top_words: "['Steak', 'with', 'Tenderloin', 'Porterhouse', 'Sirloin']"},
 {location: [34.0, -112.0],
  top_words: "['with', 'Steak', 'Sirloin', 'Broiled', 'Chicken']"},
 {location: [34.0, -111.0],
  top_words: "['and', 'Fried', 'Onions', 'Steak', 'Stewed']"},
 {location: [34.0, -87.0],
  top_words: "['Cold', 'Fried', 'Eggs', 'Cakes', 'Bacon']"},
 {location: [34.0, -84.0],
  top_words: "['Roast', 'Sauce', 'of', 'on', 'Chicken']"},
 {location: [35.0, -112.0],
  top_words: "['&', 'Cold', 'potatoe', 'Oatmeal', 'porridge']"},
 {location: [35.0, -97.0],
  top_words: "['Fried', 'Coffee', 'Oat', 'Meal', 'Mash']"},
 {location: [35.0, -93.0],
  top_words: "['au', 'a', 'la', 'en', 'potatoes']"},
 {location: [35.0, -90.0],
  top_words: "['de', 'a', 'la', 'CAFE', 'glaces']"},
 {location: [35.0, -85.0],
  top_words: "['de', 'a', 'Boiled', 'with', 'la']"},
 {location: [35.0, -84.0],
  top_words: "['Cold', 'and', 'a', 'la', 'Rice']"},
 {location: [35.0, -81.0],
  top_words: "['Sauce', 'Roast', 'of', 'a', 'la']"},
 {location: [35.0, -79.0],
  top_words: "['to', 'order', 'Broiled', 'Fried', 'Omelettes,']"},
 {location: [35.0, 140.0],
  top_words: "['Cold', 'roast', 'pie', 'lamb', 'pot']"},
 {location: [36.0, -106.0],
  top_words: "['of', 'Oyster', 'Celery', 'Canape', 'Caviar']"},
 {location: [36.0, -105.0],
  top_words: "['A', 'DE', 'LA', 'BOEUF', 'POTAGE']"},
 {location: [36.0, -98.0],
  top_words: "['Beef', 'Corned', 'on', 'Toast', 'or']"},
 {location: [36.0, -96.0],
  top_words: "['of', 'with', 'Chicken', 'and', 'a']"},
 {location: [36.0, -94.0],
  top_words: "['-', 'Cakes', 'Sauce', 'Coffee', 'Fried']"},
 {location: [36.0, -87.0],
  top_words: "['a', 'la', 'of', 'Sauce', 'Roast']"},
 {location: [36.0, -84.0],
  top_words: "['style', 'with', 'Fruits', 'Chicken', 'Sauce']"},
 {location: [36.0, -83.0],
  top_words: "['Truffelsauce', 'Cold', 'Boiled', 'St.', 'Germain']"},
 {location: [36.0, -80.0],
  top_words: "['of', 'potatoes', 'with', 'Apple', 'Chicken']"},
 {location: [36.0, -79.0],
  top_words: "['Chateau', 'and', 'Whiskey', 'Mashed', 'potatoes']"},
 {location: [36.0, -5.0],
  top_words: "['Boiled', 'Sauce', 'Roast', 'of', 'Corn']"},
 {location: [36.0, 140.0],
  top_words: "['of', 'Boiled', 'potatoes', 'Cream', 'Cheese']"},
 {location: [37.0, -122.0],
  top_words: "['Potatoes', 'with', 'Omelette', 'potatoes', 'Eggs,']"},
 {location: [37.0, -119.0],
  top_words: "['a', 'la', 'Roastbeef', 'Kase', 'Kaffee']"},
 {location: [37.0, -96.0], 'top_words': "['de', 'la', 'a', 'of', '&']"},
 {location: [37.0, -95.0],
  top_words: "['&', 'Dry', 'Champagne,', 'Liqueur,', 'of']"},
 {location: [37.0, -94.0],
  top_words: "['de', 'Sauce', 'Potage', 'aux', 'fines']"},
 {location: [37.0, -80.0], 'top_words': "['and', 'of', '.', 'de', 'sauce']"},
 {location: [37.0, -77.0],
  top_words: "['a', 'la', 'Beefsteak,', 'in', 'nach']"},
 {location: [37.0, -76.0],
  top_words: "['Cold', 'Potatoes', 'Corned', 'and', 'Pork']"},
 {location: [37.0, -4.0],
  top_words: "['and', 'Salad', 'Potted', 'Cheese', 'Barley']"},
 {location: [37.0, 28.0], 'top_words': "['Breakfast']"},
 {location: [38.0, -123.0],
  top_words: "['sauce', 'Blue', 'Points', 'on', 'Deep']"},
 {location: [38.0, -122.0],
  top_words: "['with', 'of', 'Sauce', 'a', 'de']"},
 {location: [38.0, -95.0], 'top_words': "['a', 'la', 'de', 'Ex', 'Old']"},
 {location: [38.0, -88.0],
  top_words: "['Cresta', 'Blanca', 'Souvenir', 'Haute', 'Sauterne']"},
 {location: [38.0, -86.0], 'top_words': "['a', 'la', 'of', 'from', 'Beef']"},
 {location: [38.0, -84.0],
  top_words: "['and', 'Fried', 'fried', 'Oranges.', 'Hominy']"},
 {location: [38.0, -77.0],
  top_words: "['of', 'cream', 'with', 'Salad', 'Sauce']"},
 {location: [38.0, -75.0],
  top_words: "['of', 'a', 'Puff-Paste', 'in', 'Rolls']"},
 {location: [38.0, -5.0], 'top_words': "['of', 'a', 'Celery', 'la', 'and']"},
 {location: [38.0, 15.0],
  top_words: "['of', 'Box', 'Cigarettes', 'ten', 'Chateau']"},
 {location: [38.0, 22.0], 'top_words': "['a', 'la', 'of', 'with', 'and']"},
 {location: [39.0, -121.0],
  top_words: "['Sauce', 'Cheese', 'of', '&', 'Boiled']"},
 {location: [39.0, -120.0],
  top_words: "['&', 'u.', 'Consomme', 'Lloyd-,', 'Gerauch.']"},
 {location: [39.0, -105.0],
  top_words: "['Kartoffeln', 'of', 'Fried', 'Beefsteak', 'Sauce']"},
 {location: [39.0, -97.0],
  top_words: "['Cream', 'of', 'au', 'potatoes', 'Little']"},
 {location: [39.0, -96.0],
  top_words: "['in', '&', 'a', 'Rothschild', 'la']"},
 {location: [39.0, -95.0],
  top_words: "['Potatoes', 'a', 'French', 'Fried', 'of']"},
 {location: [39.0, -92.0],
  top_words: "['beef', 'Roast', 'of', 'Ham', 'Salad']"},
 {location: [39.0, -90.0], 'top_words': "['a', 'de', 'with', 'la', 'of']"},
 {location: [39.0, -85.0],
  top_words: "['Sauce', '&', 'Potatoes', 'of', 'Fried']"},
 {location: [39.0, -84.0],
  top_words: "['Sauce', 'Native', 'of', 'Spring', 'Coffee']"},
 {location: [39.0, -79.0],
  top_words: "['Cold', 'cake', 'Stewed', 'Cake', 'of']"},
 {location: [39.0, -77.0], 'top_words': "['with', 'a', 'la', 'of', 'and']"},
 {location: [39.0, -76.0],
  top_words: "['of', 'Cream', 'Roast', 'Sliced', 'and']"},
 {location: [39.0, -74.0],
  top_words: "['with', 'Sauce', 'Roast', 'Chicken', 'Eggs,']"},
 {location: [39.0, -9.0],
  top_words: "['&', 'Two', 'Beans', 'with', 'cake']"},
 {location: [40.0, -120.0],
  top_words: "['Chicken', 'en', 'Tasse', 'salad', 'Cold']"},
 {location: [40.0, -107.0],
  top_words: "['and', 'with', 'Cream', 'of', 'a']"},
 {location: [40.0, -105.0],
  top_words: "['Cold', 'Sauce', 'of', 'Potatoes', 'and']"},
 {location: [40.0, -88.0],
  top_words: "['de', 'con', 'fritas', 'a', 'la']"},
 {location: [40.0, -87.0],
  top_words: "['Roast', 'Cheese', 'beef', 'Boiled', 'Mutton']"},
 {location: [40.0, -86.0],
  top_words: "['of', 'Pudding', 'Boiled', 'Tongue', 'Creme']"},
 {location: [40.0, -83.0],
  top_words: "['Salad', 'with', 'cream', 'salad', 'ice']"},
 {location: [40.0, -80.0],
  top_words: "['Fried', 'Kartoffeln', '&', 'and', 'a']"},
 {location: [40.0, -78.0],
  top_words: "['&', 'champagne,', 'Dry', '-', 'Water']"},
 {location: [40.0, -77.0], 'top_words': "['of', 'a', 'la', 'and', 'Sauce']"},
 {location: [40.0, -76.0],
  top_words: "['sauce', 'and', 'Salad', 'Sweet', 'Boiled']"},
 {location: [40.0, -75.0],
  top_words: "['of', 'with', '&', 'Boiled', 'Beef']"},
 {location: [40.0, -74.0],
  top_words: "['&', 'Water', 'Dry', 'Extra', 'Co.,']"},
 {location: [41.0, -112.0],
  top_words: "['in', 'of', 'Fried', 'Potatoes', 'Corn']"},
 {location: [41.0, -105.0], 'top_words': "['a', 'de', 'Sauce', 'la', '&']"},
 {location: [41.0, -96.0],
  top_words: "['de', 'Boiled', 'Cold', 'a', 'la']"},
 {location: [41.0, -91.0],
  top_words: "['LITTLE', 'NECK', 'CLAMS,', 'Tenderloin', 'La']"},
 {location: [41.0, -83.0],
  top_words: "['a', 'Glace', 'Consomme', 'Tapioca', 'Soup']"},
 {location: [41.0, -82.0],
  top_words: "['&', 'Water', 'Pts./Qts.', 'Dry', 'Extra']"},
 {location: [41.0, -78.0],
  top_words: "['&', 'Dry', 'Beef', 'and', 'Extra']"},
 {location: [41.0, -77.0],
  top_words: "['Broiled', 'Cold', 'Fried', 'Boiled', 'with']"},
 {location: [41.0, -76.0],
  top_words: "['Pudding', 'Boiled', 'Stewed', 'of', 'Beef']"},
 {location: [41.0, -75.0],
  top_words: "['with', 'Broiled', 'and', 'Fried', 'Omelette,']"},
 {location: [41.0, -74.0], 'top_words': "['a', 'and', 'with', 'la', 'of']"},
 {location: [41.0, -73.0],
  top_words: "['&', 'Dry', 'Liqueur,', 'Water', 'Light']"},
 {location: [41.0, -72.0],
  top_words: "['&', 'quality', 'seal)', 'Dry', 'Claret']"},
 {location: [41.0, -71.0],
  top_words: "['in', 'with', 'Sauce', 'of', 'Chicken']"},
 {location: [41.0, 2.0],
  top_words: "['Pommes', 'Fonslantes', 'Salmon', 'Fruit', 'Pudding']"},
 {location: [41.0, 14.0],
  top_words: "['Mashed', 'and', 'Boiled', 'Cream', 'Pie']"},
 {location: [42.0, -88.0],
  top_words: "['with', 'per', 'and', 'Fried', 'Potatoes']"},
 {location: [42.0, -85.0],
  top_words: "['-', 'Sauce', 'Pommes', 'OYSTERS', 'ON']"},
 {location: [42.0, -83.0], 'top_words': "['Cold', 'a', 'la', 'Salad', '&']"},
 {location: [42.0, -82.0],
  top_words: "['Sandwich', 'Oysters:', '2', 'Omelette', 'and']"},
 {location: [42.0, -80.0],
  top_words: "['&', 'Beef', 'with', 'Pie', 'Pudding']"},
 {location: [42.0, -79.0],
  top_words: "['salat', 'a', 'Smoked', 'salad', 'la']"},
 {location: [42.0, -78.0],
  top_words: "['and', 'Beefsteak,', 'Kartoffeln', 'Eggs', 'Fried']"},
 {location: [42.0, -77.0],
  top_words: "['Beef', 'Cheese', 'a', 'la', '&']"},
 {location: [42.0, -74.0], 'top_words': "['A', 'LA', 'Sauce', 'a', 'de']"},
 {location: [42.0, -73.0],
  top_words: "['Roast', 'Cheese', 'of', 'beef', 'Boiled']"},
 {location: [42.0, -72.0],
  top_words: "['Cold', '&', 'Mutton', 'Coffee', 'Boiled']"},
 {location: [42.0, -71.0],
  top_words: "['of', '&', 'with', 'Boiled', 'and']"},
 {location: [42.0, -70.0],
  top_words: "['de', 'Oeufs', 'a', 'la', 'Sole,']"},
 {location: [42.0, 12.0], 'top_words': "['de', 'of', 'a', 'Sauce', 'la']"},
 {location: [42.0, 13.0],
  top_words: "['Fried', 'Potatoes', 'Broiled', 'bread', '&']"},
 {location: [43.0, -112.0],
  top_words: "['Cheese', 'OYSTERS', 'ON', 'HALF', 'SHELL']"},
 {location: [43.0, -96.0],
  top_words: "['-', 'Cream', 'of', 'Roast', 'Turkey']"},
 {location: [43.0, -88.0],
  top_words: "['Roast', 'Cheese', 'Potatoes', 'with', 'Fried']"},
 {location: [43.0, -85.0],
  top_words: "['Cold', 'roast', 'beef', 'Soup,', 'Maccaroni']"},
 {location: [43.0, -84.0],
  top_words: "['Broiled', 'Baked', 'with', 'Potatoes', 'Clam']"},
 {location: [43.0, -83.0],
  top_words: "['a', 'la', 'Consomme', 'Marquisette', 'Sterlets']"},
 {location: [43.0, -81.0],
  top_words: "['Bouillon', 'mit', 'Sternnudeln', 'Gek.', 'Kabeljau']"},
 {location: [43.0, -79.0],
  top_words: "['de', 'au', '(Champagne)', '&', 'Beef']"},
 {location: [43.0, -78.0],
  top_words: "['Roast', 'Cheese', 'Chicken', 'Baked', 'Pork']"},
 {location: [43.0, -76.0], 'top_words': "['&', 'Cold', 'a', 'la', 'of']"},
 {location: [43.0, -75.0],
  top_words: "['Cold', 'Potatoes', 'la', 'Cheese', 'a']"},
 {location: [43.0, -74.0],
  top_words: "['with', 'Cold', '&', 'and', 'Potatoes']"},
 {location: [43.0, -71.0],
  top_words: "['de', 'with', 'a', 'FROID:', 'Cold:']"},
 {location: [43.0, -2.0],
  top_words: "['sauce', 'Rice', 'Fried', 'Sauce', 'Boiled']"},
 {location: [43.0, 11.0],
  top_words: "['of', 'Squab', 'Chicken', 'Fresh', 'Hot']"},
 {location: [44.0, -80.0],
  top_words: "['Lamb', 'Beef', 'salad', 'of', 'Corned']"},
 {location: [44.0, -79.0],
  top_words: "['and', 'Chateau', 'Art', 'beef', 'St.']"},
 {location: [44.0, -74.0],
  top_words: "['of', 'Sauce', 'with', 'a', 'la']"},
 {location: [44.0, -73.0],
  top_words: "['Art.', 'Puterbraten,', 'Kronsbeersauce', 'with', 'Coffee']"},
 {location: [44.0, -72.0],
  top_words: "['mit', 'with', 'Roastbeef,', 'Omelette', 'Geflugelleber']"},
 {location: [44.0, -71.0], 'top_words': "['de', 'a', 'la', 'aux', 'Pie']"},
 {location: [44.0, -70.0],
  top_words: "['with', '&', 'Cold', 'of', 'Broiled']"},
 {location: [44.0, -68.0],
  top_words: "['Sauce', 'of', 'POTATOES', 'Mashed', 'Wafers']"},
 {location: [44.0, 5.0],
  top_words: "['of', 'Baked', 'Potatoes', 'Cheese', 'Roast']"},
 {location: [44.0, 6.0],
  top_words: "['Salad', 'Lucullus', 'Charlotte', 'Russe', 'Roastbeef,']"},
 {location: [44.0, 7.0],
  top_words: "['and', 'Beef', 'Cheese,', 'Chicken', 'Pickled']"},
 {location: [45.0, -122.0],
  top_words: '[\'de\', \'a\', \'la\', \'Hors\', "d\'Oeuvres"]'},
 {location: [45.0, -118.0],
  top_words: "['Roast', 'Rumpsteak', 'a', 'la', 'provencale']"},
 {location: [45.0, -93.0],
  top_words: "['Coffee', 'and', 'Roast', 'Roastbeef', 'Fried']"},
 {location: [45.0, -85.0],
  top_words: "['&', 'American', 'Brut', 'Still,', 'Lager,']"},
 {location: [45.0, -84.0],
  top_words: "['and', 'Fruit', 'Coffee', 'or', 'Tea']"},
 {location: [45.0, -76.0],
  top_words: "['a', 'la', 'Sauce', 'Hollandaise', 'Suppe']"},
 {location: [45.0, -74.0],
  top_words: "['and', 'potatoes', 'Asparagus', 'Stewed', 'tomatoes']"},
 {location: [45.0, -73.0],
  top_words: "['Sauce', 'of', 'Puree', 'Sima', 'Bean']"},
 {location: [45.0, -67.0], 'top_words': "['of', 'au', 'a', 'la', 'Boiled']"},
 {location: [45.0, 9.0], 'top_words': "['la', 'a', '&', 'en', 'Chateau']"},
 {location: [46.0, -123.0],
  top_words: "['of', 'a', 'la', 'with', 'Sauce']"},
 {location: [46.0, -122.0],
  top_words: "['Cold', 'Hot', 'Corn', 'Meal', 'Mashed']"},
 {location: [46.0, -100.0],
  top_words: "['Brown', 'Boiled', 'sauce', 'of', 'potatoes']"},
 {location: [46.0, -85.0],
  top_words: "['Broiled', 'Cold', 'Potatoes', 'Preserves', 'Fried']"},
 {location: [46.0, -75.0],
  top_words: "['with', 'Broiled', 'and', 'or', 'Pie']"},
 {location: [46.0, -74.0], 'top_words': "['of', '-', 'a', 'la', 'with']"},
 {location: [46.0, -1.0],
  top_words: "['Celeri', 'Clams', 'en', 'Coquille', 'Creme']"},
 {location: [46.0, 2.0],
  top_words: "['Boiled', 'au', 'Sauce', 'sauce', 'and']"},
 {location: [46.0, 5.0],
  top_words: "['and', 'Beef', 'potatoes', 'Mashed', 'Redfish']"},
 {location: [46.0, 6.0],
  top_words: "['and', 'with', '-', 'toasted', 'Soup']"},
 {location: [46.0, 8.0],
  top_words: "['P.', 'Cold', 'Okra', 'Soup', 'Mutton']"},
 {location: [46.0, 10.0],
  top_words: "['a', 'of', 'la', 'Raw', 'Oysters']"},
 {location: [47.0, -122.0],
  top_words: "['Fried', 'Boiled', 'Cold', 'porridge', 'fish']"},
 {location: [47.0, -117.0],
  top_words: "['Omelette,', 'Eggs,', 'Potatoes,', 'Roast', 'Oysters,']"},
 {location: [47.0, -97.0],
  top_words: "['of', 'Sauce', 'with', 'Cream', 'Cold']"},
 {location: [47.0, -71.0],
  top_words: "['a', 'la', 'aux', 'Jambon,', 'Salade']"},
 {location: [47.0, 1.0],
  top_words: "['au', 'Roast', 'of', 'Pie', 'sauce']"},
 {location: [47.0, 7.0],
  top_words: "['with', 'Chicken', 'and', 'Pickled', 'Sauce']"},
 {location: [47.0, 8.0], 'top_words': "['-', 'de', 'of', 'Sauce', 'a']"},
 {location: [47.0, 9.0], 'top_words': "['de', 'a', 'of', 'aux', 'la']"},
 {location: [47.0, 19.0], 'top_words': "['Sauce', 'a', 'la', '&', 'and']"},
 {location: [48.0, -123.0],
  top_words: "['de', 'Boeuf', 'a', 'la', 'Huitres']"},
 {location: [48.0, -121.0],
  top_words: "['Mutton', 'Potatoes', 'Broiled', 'and', 'Fried']"},
 {location: [48.0, -117.0],
  top_words: "['Pickled', 'Sauce', 'Roast', 'Baked', 'and']"},
 {location: [48.0, -4.0],
  top_words: "['sauce', 'of', 'Queen', 'Boiled', 'jelly']"},
 {location: [48.0, -3.0], 'top_words': "['[N/A]', 'with', 'of', 'a', 'la']"},
 {location: [48.0, 7.0],
  top_words: "['Broiled', 'Fresh', 'Mackerel', 'Sliced', 'Tomatoes']"},
 {location: [48.0, 8.0],
  top_words: "['de', 'Sorbet', 'Chartreuse', 'Caille', 'Farcie']"},
 {location: [48.0, 12.0],
  top_words: "['Fried', 'Omelettes', 'Broiled', 'Potatoes', 'a']"},
 {location: [48.0, 13.0],
  top_words: "['a', 'Preserved', 'Chicken', 'la', 'with']"},
 {location: [48.0, 16.0],
  top_words: "['Cold', 'Boiled', 'Beef', 'Potatoes', 'Fried']"},
 {location: [49.0, -123.0],
  top_words: "['of', 'Smoked', 'Roast', 'and', '&']"},
 {location: [49.0, 2.0],
  top_words: "['la', 'a', 'with', 'of', 'Potatoes']"},
 {location: [49.0, 8.0],
  top_words: "['of', 'cream', 'with', 'au', 'French']"},
 {location: [49.0, 9.0],
  top_words: "['per', 'bottle', 'glass', 'Ale,', 'Boiled']"},
 {location: [49.0, 11.0], 'top_words': "['a', 'la', 'of', 'au', '-']"},
 {location: [50.0, 8.0],
  top_words: "['Boiled', 'Roast', 'Fruit', 'Potato', 'Soup']"},
 {location: [50.0, 9.0],
  top_words: "['with', 'of', 'Roast', 'Sauce', 'a']"},
 {location: [50.0, 11.0],
  top_words: "['&', 'Sauce', 'Cafe', 'noir', 'Dessert']"},
 {location: [50.0, 14.0],
  top_words: "['Cocktail', 'Winter', 'Harbors', 'Chateau', 'Yquem']"},
 {location: [51.0, -2.0],
  top_words: "['of', 'Potatoes', 'Apples', 'Sauce', 'and']"},
 {location: [51.0, -1.0],
  top_words: "['Broiled', 'Eggs', 'Potatoes', 'Cold', 'Fried']"},
 {location: [51.0, -0.0],
  top_words: "['with', 'of', 'Cream', 'Omelette,', 'Cakes']"},
 {location: [51.0, 3.0],
  top_words: "['Sauce', 'la', 'of', 'Fowls', 'Baked']"},
 {location: [51.0, 4.0], 'top_words': "['a', 'la', 'of', 'mit', 'beef']"},
 {location: [51.0, 7.0],
  top_words: "['eggs', 'Eggs', 'Breakfast', 'Baked', 'Fried']"},
 {location: [52.0, -1.0],
  top_words: "['&', 'of', 'Sauce', 'Pickled', 'Walnuts']"},
 {location: [52.0, -0.0],
  top_words: "['with', 'a', 'la', 'Broiled', 'and']"},
 {location: [52.0, 4.0], 'top_words': "['Potatoes,', 'a', '&', 'la', 'of']"},
 {location: [52.0, 5.0],
  top_words: "['Broiled', 'Fresh', 'Fried', 'to', 'order']"},
 {location: [52.0, 8.0],
  top_words: "['de', 'Clovis', 'Creme', 'Volaille', 'a']"},
 {location: [52.0, 11.0],
  top_words: "['a', 'Consomme', 'Pickled', 'Cheese', 'Pasteten']"},
 {location: [52.0, 12.0],
  top_words: "['&', 'Kraftbruhe', 'and', 'Kerbel-Suppe', 'Gebackener']"},
 {location: [52.0, 13.0], 'top_words': "['of', 'a', 'au', 'en', 'broiled']"},
 {location: [53.0, -74.0],
  top_words: "['Sauce', 'of', 'Pudding', 'Roast', '&']"},
 {location: [53.0, -6.0],
  top_words: "['Art', 'in', 'Kabeljau,', 'Robertsauce,', 'zerlassene']"},
 {location: [53.0, -3.0],
  top_words: "['of', 'cheese', 'Celery', 'Caviar', 'on']"},
 {location: [53.0, -2.0],
  top_words: "['Fried', 'milk', '&', 'Rice', 'Eggs']"},
 {location: [53.0, 1.0],
  top_words: "['of', '[Cake]', '[Ice', 'Cream]', 'a']"},
 {location: [53.0, 9.0],
  top_words: "['Beefsteak,', 'Yorkshire', 'potatoes', 'Kuchen', 'la']"},
 {location: [53.0, 13.0],
  top_words: "['Pts./Qts.', 'per', 'glass', 'Pts.', 'and']"},
 {location: [54.0, -99.0],
  top_words: "['with', 'a', 'Sauce', 'Roast', 'la']"},
 {location: [54.0, -2.0],
  top_words: "['a', 'la', 'aux', 'Jambon,', 'Radis,']"},
 {location: [54.0, 10.0], 'top_words': "['a', 'la', 'Sauce', 'and', 'of']"},
 {location: [55.0, -2.0],
  top_words: "['Roastbeef', 'Rumpsteak,', 'Succotash', 'Irish', 'stew']"},
 {location: [56.0, -3.0],
  top_words: "['&', 'Fried', 'Fruit', 'Fine', 'Hominy']"},
 {location: [56.0, 13.0],
  top_words: "['Cold', 'with', 'Chicken', 'Extra', 'Fried']"},
 {location: [60.0, 5.0],
  top_words: "['&', 'Mashed', 'Bouillon', 'Gebr.', 'Succotash']"},
 {location: [60.0, 11.0],
  top_words: "['or', 'with', 'Art', 'nach', 'Sauce']"},
 {location: [60.0, 30.0],
  top_words: "['Potatoes-', 'au', 'French', 'Salad', 'a']"},
 {location: [62.0, -149.0],
  top_words: "['in', 'Roast', 'Lima', 'mit', 'beef']"},
 {location: [63.0, 10.0],
  top_words: "['a', 'la', 'Boiled', 'Sauce', 'de']"}];

var utensilIcon = L.icon({
  iconUrl: 'fork-icon-png-14.png',
  iconSize:     [55, 80], 
  iconAnchor:   [27, 80], 
  popupAnchor:  [0, -76]
});

for (var i = 0; i < menus.length; i++) {
  var menu = menus[i];
  L.marker(menu.location, {icon:utensilIcon})
    .bindPopup("<h1>" + menu.top_words+ "</h1>")
    .addTo(myMap);
}
